services:
  postgres:
    image: postgres:16
    container_name: postgres-popjav
    environment:
      POSTGRES_DB: ${PERSISTENCE_DB_NAME}
      POSTGRES_USER: ${PERSISTENCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${PERSISTENCE_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PERSISTENCE_DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - popjav-network

  consul:
    image: hashicorp/consul:1.21.3
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - popjav-network

volumes:
  postgres-data:

networks:
  popjav-network:
    driver: bridge