services:
  postgres:
    image: postgres:16
    container_name: postgres-popjav
    environment:
      POSTGRES_DB: ${PERSISTENCE_DB_NAME}
      POSTGRES_USER: ${PERSISTENCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${PERSISTENCE_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PERSISTENCE_DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - popjav-network

  mongo:
    image: mongo:7
    container_name: mongo-popjav
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${COMMENT_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${COMMENT_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${COMMENT_DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - popjav-network

  consul:
    image: hashicorp/consul:1.21.3
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - popjav-network

  persistence-service:
    image: enzogavini/persistence-service:latest
    container_name: persistence-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      PERSISTENCE_DB_HOST: postgres-popjav
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - popjav-network

  auth-service:
    image: enzogavini/auth-service:latest
    container_name: auth-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    depends_on:
      consul:
        condition: service_healthy
      persistence-service:
        condition: service_started
    networks:
      - popjav-network

  content-service:
    image: enzogavini/content-service:latest
    container_name: content-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    depends_on:
      consul:
        condition: service_healthy
      persistence-service:
        condition: service_started
    networks:
      - popjav-network

  quiz-service:
    image: enzogavini/quiz-service:latest
    container_name: quiz-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    depends_on:
      consul:
        condition: service_healthy
      persistence-service:
        condition: service_started
    networks:
      - popjav-network

  comment-service:
    image: enzogavini/comment-service:latest
    container_name: comment-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      COMMENT_DB_HOST: mongo-popjav
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    depends_on:
      consul:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - popjav-network

  api-gateway:
    image: enzogavini/api-gateway:latest
    container_name: api-gateway
    env_file: .env
    environment:
      CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - popjav-network

  ui-service:
    image: enzogavini/ui-service:latest
    container_name: ui-service
    env_file: .env
    environment:
      CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"
    ports:
      - "${UI_SERVICE_PORT}:${UI_SERVICE_PORT}"
    depends_on:
      consul:
        condition: service_healthy
      api-gateway:
        condition: service_started
    networks:
      - popjav-network

volumes:
  postgres-data:
  mongo-data:

networks:
  popjav-network:
    driver: bridge
